export const stock_name_map = {
	'AAPL':'Apple',
	'AXP':'American Express',
	'BA':'Boeing',
	'CAT':'Caterpillar',
	'CSCO':'Cisco Systems',
	'CVX':'Chevron',
	'KO':'Coca-Cola',
	'DD':'DuPont',
	'XOM':'ExxonMobil',
	'GE':'General Electric',
	'GS':'Goldman Sachs',
    'HD':'Home Depot',
    'IBM':'IBM',
    'INTC':'Intel',
    'JNJ':'Johnson & Johnson',
    'JPM':'JPMorgan Chase',
    'MCD':'McDonald\'s',
    'MMM':'3M Company',
    'MRK':'Merck',
    'MSFT':'Microsoft',
    'NKE':'Nike',
    'PFE':'Pfizer',
    'PG':'Procter & Gamble',
    'TRV':'The Travelers',
    'UNH':'UnitedHealth',
    'UTX':'United Technologies',
    'V':'Visa',
    'VZ':'Verizon',
    'WMT':'Wal-Mart',
    'DIS':'Walt Disney'
}
